### ISSUE TITLE
关于GPS无法搜星的问题 GPS Problems.

### ISSUE THREAD

**Issue by etnperlong** [GuaiYiHu/android_kernel_xiaomi_leo#1]
我在XDA论坛上找到了关于GPS问题讨论的帖子：
https://forum.xda-developers.com/showpost.php?p=67871820&postcount=37

帖子中说到160712版本的Mokee修复了GPS问题，在39楼也有别的用户证实
然而在之后的Release版本中，这个问题又重新出现了。
所以我正在尝试在GitHub查找这段时间提交的魔趣，设备树以及内核代码，希望早日能够修复这个问题。

I found a thread about GPS problems on xda-developers:
https://forum.xda-developers.com/showpost.php?p=67871820&postcount=37
It said that the problem had been fixed in Mokee 160712 but it showed again in later release build.
I hope the problem can be fixed, and now I am trying to search the commits of Mokee, device tree and kernel in GitHub.

**Comment by GuaiYiHu** [comment]
fixed
