### ISSUE TITLE
es9018

### ISSUE THREAD

**Issue by lrinQVQ** [GuaiYiHu/android_kernel_xiaomi_leo#2]
直接使用4c的内核理论上问题不大(毕竟也就是多8992 dts和少8992dts的区别)= =,但是目前开源的kernel都没有es9018的支持

**Comment by GuaiYiHu** [comment]
然而HiFi这种东西宁可没有的、默认MIUI打开就会滋滋滋滋滋~~~~

**Comment by lrinQVQ** [comment]
23333欸嘿 没有发现这类问题欸

**Comment by lrinQVQ** [comment]
😂我朋友的note pro hifi没问题啊～索尼大法好～
